### ISSUE TITLE
ppx for OCaml >= 4.04

### ISSUE THREAD

**Issue by copy** [mfp/ocaml-sqlexpr#22]
Support for newer versions of OCaml would be nice, currently only 0.6.1 is installable on 4.04.

**Comment by mfp** [comment]
On Tue, Apr 25, 2017 at 11:32:40AM -0700, Fabian wrote:
> Support for newer versions of OCaml would be nice, currently only 0.6.1 is installable on 4.04.

I'm awfully behind the curve wrt. ppx. Looks like I'll have to look into
ocaml-migrate-parsetree for a long-term solution.

-- 
Mauricio Fernández

**Comment by j0sh** [comment]
Luckily it seems that there are no changes needed to support 4.04 and 4.04. Only the constraint in opam needs to be updated. See https://github.com/mfp/ocaml-sqlexpr/pull/21/commits/855403fd7dbaa1b2dfb2f4fe0740cc34ca9161b0

**Comment by mfp** [comment]
Since `ocaml-migrate-parsetree` is not required atm., a release with support for 4.02 to 4.05 (tested against 4.05.0+beta2) will follow in the new few days.

**Comment by copy** [comment]
I can confirm this is working with the latest release (0.8.0). Thanks!

**Comment by mfp** [comment]
On Thu, May 11, 2017 at 11:40:56AM -0700, Fabian wrote:
> I can confirm this is working with the latest release (0.8.0). Thanks!

Good to hear, and thank you for the extra validation point.

For once, we're not behind the times since we even support the (unreleased)
4.05 (as of +beta2) :-)

-- 
Mauricio Fernández
