### ISSUE TITLE
Building of doc fail for OCaml 4.04.0

### ISSUE THREAD

**Issue by rixed** [mfp/ocaml-sqlexpr#23]
With this error message:

````
+ /home/rixed/.opam/ramen/bin/ocamlfind ocamldoc -dump src/sqlexpr_sqlite.odoc -package csv -package estring -package lwt -syntax camlp4o -package lwt.syntax -package lwt.unix -package sqlite3 -package threads -package unix -I +threads -I src src/sqlexpr_sqlite.mli
ocamlfind: [WARNING] Package `threads' signals error: Missing -thread or -vmthread switch
File "/home/rixed/.opam/ramen/build/sqlexpr.0.6.1/_build/src/sqlexpr_sqlite.mli", line 144, character 0:
[init] is not a valid parameter identificator in "@param [init] function to be applied to [Sqlite3.db] handle(s) before
    * they are used (can be used to register functions or initialize schema in
    * in-mem tables."
File "/home/rixed/.opam/ramen/build/sqlexpr.0.6.1/_build/src/sqlexpr_sqlite.mli", line 149, character 0:
[init] is not a valid parameter identificator in "@param [init] function to be applied to [Sqlite3.db] handle(s) before
    * they are used (can be used to register functions or initialize schema in
    * in-mem tables."
2 error(s) encountered
````

**Comment by rixed** [comment]
Note that this is for version 0.6.1 ; I haven't tested 0.7.1

**Comment by mfp** [comment]
On Sat, Apr 29, 2017 at 11:25:25AM -0700, Cedric Cellier wrote:
> With this error message:
[...]
> File "/home/rixed/.opam/ramen/build/sqlexpr.0.6.1/_build/src/sqlexpr_sqlite.mli", line 144, character 0:
> [init] is not a valid parameter identificator in "@param [init] function to be applied to [Sqlite3.db] handle(s) before
>     * they are used (can be used to register functions or initialize schema in
>     * in-mem tables."

Thank you reporting this issue; I rarely refer to (let alone build) the
ocamldoc documentation, so it could have gone unnoticed for a long time :)

I've verified there are no other serious issues with the docs (ocamldoc
completes) after the fix.

-- 
Mauricio Fernández
