### ISSUE TITLE
jbuilder support

### ISSUE THREAD

**Issue by Freyr666** [mfp/ocaml-sqlexpr#26]
Currently sqlexpr.ppx doesn't work well with jbuilder

```
File "db.ml", line 8, characters 23-30:
Error: Uninterpreted extension 'sqlinit'.
```

I'm not aware of what should be fixed to make it work, if there is some workaround I'd be glad to know about it.

**Comment by j0sh** [comment]
JBuilder expects ppx to use ocaml-migrate-parseree. Adding ocaml-migrate-parsetree support to sqlexpr been on my todo list for a while, but if there's actually interest from others, then I can look at doing it sooner. (Of course, patches are welcome anytime!)

**Comment by Freyr666** [comment]
@j0sh, ok, I've tried to make it work with ocaml-migrate-parsetree. While migration to 'migrate-parsetree' does not require much [effort](https://github.com/Freyr666/ocaml-sqlexpr/blob/migrate-parsetree/src/ppx/ppx_sqlexpr.ml), packaging looks like such a PITA for me. I didn't manage to make it compile properly (i.e. producing driverized ppx) with oasis, and it seems the easiest way for me is just to move the whole sqlexpr to jbuilder (maybe splitting it to sqlexpr, sqlexpr-ppx and sqlexpr-camlp4). What do you think of it? Can you help me to make it work with the oasis or do you thing jbuilder migration is fine?

**Comment by mfp** [comment]
On Tue, Sep 26, 2017 at 11:01:36AM +0000, Freyr666 wrote:
> @j0sh, ok, I've tried to make it work with ocaml-migrate-parsetree. While migration to 'migrate-parsetree' does not require much [effort](https://github.com/Freyr666/ocaml-sqlexpr/blob/migrate-parsetree/src/ppx/ppx_sqlexpr.ml), packaging looks like such a PITA for me. I didn't manage to make it compile properly (i.e. producing driverized ppx) with oasis, and it seems the easiest way for me is just to move the whole sqlexpr to jbuilder (maybe splitting it to sqlexpr, sqlexpr-ppx and sqlexpr-camlp4). What do you think of it? Can you help me to make it work with the oasis or do you thing jbuilder migration is fine?

I'll look into this next weekend. I'm willing to tackle the work to keep the
old build system working because jbuilder's cross-compilation story is not
quite there yet, but the community is heavily weighting towards jbuilder, so
it makes sense to make it the default one.

PS: the link you gave is 404 -- I found your branch at
https://github.com/Freyr666/ocaml-sqlexpr/commits/migrate-parsetree
We're going to need some history rewriting before the merge ;-)

-- 
Mauricio Fernández

**Comment by Freyr666** [comment]
@mfp

>We're going to need some history rewriting before the merge ;-)

Sure, It's an experimental branch, I will make it neat and clean before PR. I've managed to make it work with jbuilder, it was quite simple, and my both ocaml and jbuilder projects work fine with it. I'll finish tests and other stuff and make PR later.

**Comment by Freyr666** [comment]
@mfp I've made a PR #27.
