### ISSUE TITLE
Get rid of the dependency on batteries

### ISSUE THREAD

**Issue by Armael** [mfp/ocaml-sqlexpr#3]
ocaml-sqlexpr only uses some functions of batteries from BatOption. I think it would be better to copy these functions to some "option.ml" file in the project, and get rid of the dependency on batteries, that some could find cumbersome.

I can make a PR for that if needed.

--Armael

**Comment by michipili** [comment]
I second this!

**Comment by Armael** [comment]
Solved by PR #4. Thanks!
