### ISSUE TITLE
Warning 4: this pattern-matching is fragile, Warning 27: unused variable rc

### ISSUE THREAD

**Issue by vog** [mfp/ocaml-sqlexpr#34]
The PPX generated code for `[%sqlcheck "sqlite"]` produces OCaml warnings, which is especially annoying for developers like myself, who prefer to enable all warnings during development, and turn them into errors.

This is a simple program to reproduce this issue:

```ocaml
module Sqlexpr = Sqlexpr_sqlite.Make(Sqlexpr_concurrency.Id)
let auto_init_db, check_db, auto_check_db = [%sqlcheck "sqlite"]
```

Result:

```
File "Test.ml", line 2, characters 46-54:
Warning 4: this pattern-matching is fragile.
It will remain exhaustive when constructors are added to type Sqlite3.Rc.t.
File "Test.ml", line 2, characters 46-54:
Warning 27: unused variable rc.
```

**Comment by mfp** [comment]
Thank you for the bug report, and I apologize for the time to respond to it.
This is fixed as of 5b22129a837.
