### ISSUE TITLE
Please push missing tags

### ISSUE THREAD

**Issue by michipili** [mfp/ocaml-sqlexpr#7]
Tags for 0.5.5 and 0.6.0 (at least) are missing, could you please push them?

**Comment by mfp** [comment]
I've pushed 0.5.4 and 0.5.5.

0.6.0 isn't released yet (the release will probably follow soon depending on the progress of the ppx stuff).

Please note that the actual release tarballs (which include the OASIS-generated build system, not included in the git repository) are [to be found the Ocaml Forge](https://forge.ocamlcore.org/frs/?group_id=190). These are the tarballs used in the OPAM repository. If you use github's, you will have to generate the build system with `oasis setup`.

**Comment by mfp** [comment]
I realized it'd been a long time since 0.5.5 and there were enough changes to justify an immediate release, so I just pushed 0.6.0 and [released on the OCaml Forge](https://forge.ocamlcore.org/frs/?group_id=190), with the OPAM release to follow in the next few days.

**Comment by michipili** [comment]
Great, thanks!
